// -----------------------------------------------------------------------------
// Copyright (c) 2023                  Qualcomm Technologies International, Ltd.
//
// Generated by /home/svc-audio-dspsw/kymera_builds/builds/2023/kymera_2312060823/kalimba/kymera/../../util/CommonParameters/DerivationEngine.py
// code v3.5, file //depot/dspsw/maor_rom_v20/util/CommonParameters/DerivationEngine.py, revision 2
// namespace {com.csr.cps.4}UnifiedParameterSchema on 2023-12-06 09:00:32 by svc-audio-dspsw
//
// input from EMPTY
// last change  by  on 
// -----------------------------------------------------------------------------
#include "noise_id_gen_c.h"

#ifndef __GNUC__ 
_Pragma("datasection CONST")
#endif /* __GNUC__ */

static unsigned defaults_noise_idNOISE_ID[] = {
   0x00000000u,			// NOISE_ID_CONFIG
   0x44000000u,			// POWER_RATIO_THRESHOLD
   0x50000000u,			// FILTER_ATTACK_TIME
   0x00656042u,			// FILTER_DECAY_TIME
   0x00400000u,			// NID_HOLD_TIMER
   0x00049BA6u,			// ED_ENVELOPE
   0x3999999Au,			// ED_RATIO
   0x00F00000u,			// ED_MIN_SIGNAL
   0xFB000000u,			// ED_MIN_MAX_ENVELOPE
   0x00500000u,			// ED_DELTA_TH
   0x000000C8u,			// ED_HOLD_FRAMES
   0x00500000u,			// ED_E_FILTER_MIN_THRESHOLD
   0x000000FAu,			// ED_E_FILTER_MIN_COUNTER_THRESHOLD
   0x47333333u,			// POWER_RATIO_ID0_THRESHOLD
   0x40CCCCCDu			// POWER_RATIO_ID1_THRESHOLD
};

unsigned *NOISE_ID_GetDefaults(unsigned capid){
	switch(capid){
		case 0x00EB: return defaults_noise_idNOISE_ID;
		case 0x40D1: return defaults_noise_idNOISE_ID;
	}
	return((unsigned *)0);
}
