@startuml inline_umlgraph_1.png
        object OPR_LC3_DECODE_SCO_ISO
        OPR_LC3_DECODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_DEC
        object OPR_LC3_DECODE_SCO_ISO_RIGHT
        OPR_LC3_DECODE_SCO_ISO_RIGHT : id = CAP_ID_LC3_SCO_ISO_DEC
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_L(0)" OPR_LC3_DECODE_SCO_ISO
        OPR_SPEAKER_RESAMPLER "IN_R(1)"<-- "OUT_R(0)" OPR_LC3_DECODE_SCO_ISO_RIGHT
        OPR_USB_AUDIO_TX "IN_L(0)"<-- "OUT_L(0)" OPR_SPEAKER_RESAMPLER
        OPR_USB_AUDIO_TX "IN_R(1)"<-- "OUT_R(1)" OPR_SPEAKER_RESAMPLER
        object EPR_ISO_FROM_AIR_LEFT #lightgreen
        OPR_LC3_DECODE_SCO_ISO "ISO_IN_L(0)" <-- EPR_ISO_FROM_AIR_LEFT
        object EPR_ISO_FROM_AIR_RIGHT #lightgreen
        OPR_LC3_DECODE_SCO_ISO_RIGHT "ISO_IN_R(0)" <-- EPR_ISO_FROM_AIR_RIGHT
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_2.png
        object OPR_APTX_LITE_DECODE_SCO_ISO
        OPR_APTX_LITE_DECODE_SCO_ISO : id = CAP_ID_APTX_LITE_SCO_ISO_DEC
        object OPR_APTX_LITE_DECODE_SCO_ISO_RIGHT
        OPR_APTX_LITE_DECODE_SCO_ISO_RIGHT : id = CAP_ID_APTX_LITE_SCO_ISO_DEC
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_L(0)" OPR_APTX_LITE_DECODE_SCO_ISO
        OPR_SPEAKER_RESAMPLER "IN_R(1)"<-- "OUT_R(0)" OPR_APTX_LITE_DECODE_SCO_ISO_RIGHT
        OPR_BASIC_PASS "IN_L(0)"<-- "OUT_L(0)" OPR_SPEAKER_RESAMPLER
        OPR_BASIC_PASS "IN_R(1)"<-- "OUT_R(1)" OPR_SPEAKER_RESAMPLER
        OPR_USB_AUDIO_TX "IN_L(0)"<-- "OUT_L(0)" OPR_BASIC_PASS
        OPR_USB_AUDIO_TX "IN_R(1)"<-- "OUT_R(1)" OPR_BASIC_PASS
        object EPR_ISO_FROM_AIR_LEFT #lightgreen
        OPR_APTX_LITE_DECODE_SCO_ISO "ISO_IN_L(0)" <-- EPR_ISO_FROM_AIR_LEFT
        object EPR_ISO_FROM_AIR_RIGHT #lightgreen
        OPR_APTX_LITE_DECODE_SCO_ISO_RIGHT "ISO_IN_R(0)" <-- EPR_ISO_FROM_AIR_RIGHT
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_3.png
        object OPR_LC3_DECODE_SCO_ISO
        OPR_LC3_DECODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_DEC
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_L(0)" OPR_LC3_DECODE_SCO_ISO
        OPR_USB_AUDIO_TX "IN_L(0)"<-- "OUT_L(0)" OPR_SPEAKER_RESAMPLER
        object EPR_ISO_FROM_AIR_LEFT #lightgreen
        OPR_LC3_DECODE_SCO_ISO "ISO_IN_L(0)" <-- EPR_ISO_FROM_AIR_LEFT
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_4.png
        object OPR_APTX_LITE_DECODE_SCO_ISO
        OPR_APTX_LITE_DECODE_SCO_ISO : id = CAP_ID_APTX_LITE_SCO_ISO_DEC
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_APTX_LITE_DECODE_SCO_ISO
        OPR_BASIC_PASS "IN(0)"<-- "OUT(0)" OPR_SPEAKER_RESAMPLER
        OPR_USB_AUDIO_TX "IN(0)"<-- "OUT(0)" OPR_BASIC_PASS
        object EPR_ISO_FROM_AIR_LEFT #lightgreen
        OPR_APTX_LITE_DECODE_SCO_ISO "ISO_IN(0)" <-- EPR_ISO_FROM_AIR_LEFT
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_5.png
        object OPR_LC3_DECODE_SCO_ISO
        OPR_LC3_DECODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_DEC
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_LEA_USB_SPLT_ISO_RX
        OPR_LEA_USB_SPLT_ISO_RX : id = CAP_ID_SPLITTER
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_L(0)" OPR_LC3_DECODE_SCO_ISO
        OPR_LEA_USB_SPLT_ISO_RX "IN(0)"<-- "OUT_L(0)" OPR_SPEAKER_RESAMPLER
        OPR_USB_AUDIO_TX "IN_L(0)"<-- "OUT_L(0)" OPR_LEA_USB_SPLT_ISO_RX
        OPR_USB_AUDIO_TX "IN_R(1)"<-- "OUT_R(1)" OPR_LEA_USB_SPLT_ISO_RX
        object EPR_ISO_FROM_AIR_LEFT #lightgreen
        OPR_LC3_DECODE_SCO_ISO "ISO_IN_L(0)" <-- EPR_ISO_FROM_AIR_LEFT
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_6.png
        object OPR_APTX_LITE_DECODE_SCO_ISO
        OPR_APTX_LITE_DECODE_SCO_ISO : id = CAP_ID_APTX_LITE_SCO_ISO_DEC
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_LEA_USB_SPLT_ISO_RX
        OPR_LEA_USB_SPLT_ISO_RX : id = CAP_ID_SPLITTER
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_L(0)" OPR_APTX_LITE_DECODE_SCO_ISO
        OPR_BASIC_PASS "IN(0)"<-- "OUT_L(0)" OPR_SPEAKER_RESAMPLER
        OPR_LEA_USB_SPLT_ISO_RX "IN(0)"<-- "OUT(0)" OPR_BASIC_PASS
        OPR_USB_AUDIO_TX "IN_L(0)"<-- "OUT_L(0)" OPR_LEA_USB_SPLT_ISO_RX
        OPR_USB_AUDIO_TX "IN_R(1)"<-- "OUT_R(1)" OPR_LEA_USB_SPLT_ISO_RX
        object EPR_ISO_FROM_AIR_LEFT #lightgreen
        OPR_APTX_LITE_DECODE_SCO_ISO "ISO_IN_L(0)" <-- EPR_ISO_FROM_AIR_LEFT
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_7.png
        object OPR_SCO_RECEIVE
        OPR_SCO_RECEIVE : id = CAP_ID_SCO_RCV
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_SCO_RECEIVE
        OPR_BASIC_PASS "IN(0)"<-- "OUT(0)" OPR_SPEAKER_RESAMPLER
        OPR_USB_AUDIO_TX "IN(0)"<-- "OUT(0)" OPR_BASIC_PASS
        object EPR_SCO_FROM_AIR #lightgreen
        OPR_SCO_RECEIVE "SCO_IN(0)" <-- EPR_SCO_FROM_AIR
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_8.png
        object OPR_SCO_RECEIVE
        OPR_SCO_RECEIVE : id = UD_CAP_ID_SWBS_DEC
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_SCO_RECEIVE
        OPR_BASIC_PASS "IN(0)"<-- "OUT(0)" OPR_SPEAKER_RESAMPLER
        OPR_USB_AUDIO_TX "IN(0)"<-- "OUT(0)" OPR_BASIC_PASS
        object EPR_SCO_FROM_AIR #lightgreen
        OPR_SCO_RECEIVE "SCO_IN(0)" <-- EPR_SCO_FROM_AIR
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_9.png
        object OPR_SCO_RECEIVE
        OPR_SCO_RECEIVE : id = CAP_ID_WBS_DEC
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_USB_AUDIO_TX
        OPR_USB_AUDIO_TX : id = CAP_ID_USB_AUDIO_TX
        OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_SCO_RECEIVE
        OPR_BASIC_PASS "IN(0)"<-- "OUT(0)" OPR_SPEAKER_RESAMPLER
        OPR_USB_AUDIO_TX "IN(0)"<-- "OUT(0)" OPR_BASIC_PASS
        object EPR_SCO_FROM_AIR #lightgreen
        OPR_SCO_RECEIVE "SCO_IN(0)" <-- EPR_SCO_FROM_AIR
        object EPR_USB_TO_HOST #lightblue
        EPR_USB_TO_HOST <-- "USB_OUT(0)" OPR_USB_AUDIO_TX
@enduml
@startuml inline_umlgraph_10.png
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_APTX_ADAPTIVE_ENCODER
        OPR_APTX_ADAPTIVE_ENCODER : id = CAP_ID_DOWNLOAD_APTX_ADAPTIVE_ENCODE
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_L(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_R(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_0(0)" OPR_BASIC_PASS
        OPR_SPEAKER_RESAMPLER "IN_R(1)"<-- "OUT_1(1)" OPR_BASIC_PASS
        OPR_APTX_ADAPTIVE_ENCODER "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_ADAPTIVE_ENCODER "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_APTX_ADAPTIVE_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_11.png
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_APTX_ADAPTIVE_ENCODER
        OPR_APTX_ADAPTIVE_ENCODER : id = CAP_ID_APTX_ADAPTIVE_R3_ENCODE
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_L(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_R(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_0(0)" OPR_BASIC_PASS
        OPR_SPEAKER_RESAMPLER "IN_R(1)"<-- "OUT_1(1)" OPR_BASIC_PASS
        OPR_APTX_ADAPTIVE_ENCODER "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_ADAPTIVE_ENCODER "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_APTX_ADAPTIVE_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_12.png
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_APTX_CLASSIC_ENCODER
        OPR_APTX_CLASSIC_ENCODER : id = CAP_ID_DOWNLOAD_APTX_CLASSIC_ENCODER
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_L(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_R(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_0(0)" OPR_BASIC_PASS
        OPR_SPEAKER_RESAMPLER "IN_R(1)"<-- "OUT_1(1)" OPR_BASIC_PASS
        OPR_APTX_CLASSIC_ENCODER "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_CLASSIC_ENCODER "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_APTX_CLASSIC_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_13.png
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_APTXHD_ENCODER
        OPR_APTXHD_ENCODER : id = CAP_ID_DOWNLOAD_APTXHD_ENCODER
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_L(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_R(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_0(0)" OPR_BASIC_PASS
        OPR_SPEAKER_RESAMPLER "IN_R(1)"<-- "OUT_1(1)" OPR_BASIC_PASS
        OPR_APTXHD_ENCODER "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_APTXHD_ENCODER "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_APTXHD_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_14.png
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_RATE_ADJUST_RIGHT
        OPR_RATE_ADJUST_RIGHT : id = CAP_ID_RATE_ADJUST
        object OPR_LC3_ENCODE_SCO_ISO
        OPR_LC3_ENCODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_ENC
        object OPR_LC3_ENCODE_SCO_ISO_RIGHT
        OPR_LC3_ENCODE_SCO_ISO_RIGHT : id = CAP_ID_LC3_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_RATE_ADJUST "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_RATE_ADJUST_RIGHT "IN_R(0)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_LC3_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_L(0)" OPR_RATE_ADJUST
        OPR_LC3_ENCODE_SCO_ISO_RIGHT "IN_R(0)"<-- "OUT_R(0)" OPR_RATE_ADJUST_RIGHT
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT_L(0)" OPR_LC3_ENCODE_SCO_ISO
        object EPR_ISO_TO_AIR_RIGHT #lightblue
        EPR_ISO_TO_AIR_RIGHT <-- "ISO_OUT_R(0)" OPR_LC3_ENCODE_SCO_ISO_RIGHT
@enduml
@startuml inline_umlgraph_15.png
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_RATE_ADJUST_RIGHT
        OPR_RATE_ADJUST_RIGHT : id = CAP_ID_RATE_ADJUST
        object OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO
        OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO : id = CAP_ID_APTX_ADAPTIVE_SCO_ISO_ENC
        object OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO_RIGHT
        OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO_RIGHT : id = CAP_ID_APTX_ADAPTIVE_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_RATE_ADJUST "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_RATE_ADJUST_RIGHT "IN_R(0)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_L(0)" OPR_RATE_ADJUST
        OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO_RIGHT "IN_R(0)"<-- "OUT_R(0)" OPR_RATE_ADJUST_RIGHT
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT_L(0)" OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO
        object EPR_ISO_TO_AIR_RIGHT #lightblue
        EPR_ISO_TO_AIR_RIGHT <-- "ISO_OUT_R(0)" OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO_RIGHT
@enduml
@startuml inline_umlgraph_16.png
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_RATE_ADJUST_RIGHT
        OPR_RATE_ADJUST_RIGHT : id = CAP_ID_RATE_ADJUST
        object OPR_APTX_LITE_ENCODE_SCO_ISO
        OPR_APTX_LITE_ENCODE_SCO_ISO : id = CAP_ID_APTX_LITE_SCO_ISO_ENC
        object OPR_APTX_LITE_ENCODE_SCO_ISO_RIGHT
        OPR_APTX_LITE_ENCODE_SCO_ISO_RIGHT : id = CAP_ID_APTX_LITE_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_RATE_ADJUST "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_RATE_ADJUST_RIGHT "IN_R(0)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_LITE_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_L(0)" OPR_RATE_ADJUST
        OPR_APTX_LITE_ENCODE_SCO_ISO_RIGHT "IN_R(0)"<-- "OUT_R(0)" OPR_RATE_ADJUST_RIGHT
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT_L(0)" OPR_APTX_LITE_ENCODE_SCO_ISO
        object EPR_ISO_TO_AIR_RIGHT #lightblue
        EPR_ISO_TO_AIR_RIGHT <-- "ISO_OUT_R(0)" OPR_APTX_LITE_ENCODE_SCO_ISO_RIGHT
@enduml
@startuml inline_umlgraph_17.png
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_LC3_ENCODE_SCO_ISO
        OPR_LC3_ENCODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_RATE_ADJUST "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_RATE_ADJUST "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_LC3_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_L(0)" OPR_RATE_ADJUST
        OPR_LC3_ENCODE_SCO_ISO "IN_R(1)"<-- "OUT_R(1)" OPR_RATE_ADJUST
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT(0)" OPR_LC3_ENCODE_SCO_ISO
@enduml
@startuml inline_umlgraph_18.png
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_APTX_LITE_ENCODE_SCO_ISO
        OPR_APTX_LITE_ENCODE_SCO_ISO : id = CAP_ID_APTX_LITE_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_RATE_ADJUST "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_RATE_ADJUST "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_LITE_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_L(0)" OPR_RATE_ADJUST
        OPR_APTX_LITE_ENCODE_SCO_ISO "IN_R(1)"<-- "OUT_R(1)" OPR_RATE_ADJUST
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT(0)" OPR_APTX_LITE_ENCODE_SCO_ISO
@enduml
@startuml inline_umlgraph_19.png
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_LEFT_RIGHT_MIXER
        OPR_LEFT_RIGHT_MIXER : id = CAP_ID_MIXER
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_LC3_ENCODE_SCO_ISO
        OPR_LC3_ENCODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_ENC
        OPR_LEFT_RIGHT_MIXER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_LEFT_RIGHT_MIXER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT(0)" OPR_LEFT_RIGHT_MIXER
        OPR_RATE_ADJUST "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_LC3_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_L(0)" OPR_RATE_ADJUST
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT(0)" OPR_LC3_ENCODE_SCO_ISO
@enduml
@startuml inline_umlgraph_20.png
        object OPR_BASIC_PASS
        OPR_BASIC_PASS : id = CAP_ID_BASIC_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_SBC_ENCODER
        OPR_SBC_ENCODER : id = CAP_ID_SBC_ENCODER
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_L(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_BASIC_PASS "IN_R(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN_L(0)"<-- "OUT_0(0)" OPR_BASIC_PASS
        OPR_SPEAKER_RESAMPLER "IN_R(1)"<-- "OUT_1(1)" OPR_BASIC_PASS
        OPR_SBC_ENCODER "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_SBC_ENCODER "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_SBC_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_21.png
        object OPR_LEFT_RIGHT_MIXER
        OPR_LEFT_RIGHT_MIXER : id = CAP_ID_MIXER
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_SOURCE_SYNC
        OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
        object OPR_SCO_SEND
        OPR_SCO_SEND : id = CAP_ID_SCO_SEND
        OPR_LEFT_RIGHT_MIXER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_LEFT_RIGHT_MIXER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_LEFT_RIGHT_MIXER
        OPR_RATE_ADJUST "IN(0)"<-- "OUT(0)" OPR_SPEAKER_RESAMPLER
        OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_RATE_ADJUST
        OPR_SCO_SEND "IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_SCO_TO_AIR #lightblue
        EPR_SCO_TO_AIR <-- "SCO_OUT(0)" OPR_SCO_SEND
@enduml
@startuml inline_umlgraph_22.png
        object OPR_LEFT_RIGHT_MIXER
        OPR_LEFT_RIGHT_MIXER : id = CAP_ID_MIXER
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_SOURCE_SYNC
        OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
        object OPR_SCO_SEND
        OPR_SCO_SEND : id = UD_CAP_ID_SWBS_ENC
        OPR_LEFT_RIGHT_MIXER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_LEFT_RIGHT_MIXER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_LEFT_RIGHT_MIXER
        OPR_RATE_ADJUST "IN(0)"<-- "OUT(0)" OPR_SPEAKER_RESAMPLER
        OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_RATE_ADJUST
        OPR_SCO_SEND "IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_SCO_TO_AIR #lightblue
        EPR_SCO_TO_AIR <-- "SCO_OUT(0)" OPR_SCO_SEND
@enduml
@startuml inline_umlgraph_23.png
        object OPR_LEFT_RIGHT_MIXER
        OPR_LEFT_RIGHT_MIXER : id = CAP_ID_MIXER
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_RATE_ADJUST
        OPR_RATE_ADJUST : id = CAP_ID_RATE_ADJUST
        object OPR_SOURCE_SYNC
        OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
        object OPR_SCO_SEND
        OPR_SCO_SEND : id = CAP_ID_WBS_ENC
        OPR_LEFT_RIGHT_MIXER "IN_0(0)"<-- "OUT_0(0)" OPR_USB_AUDIO_RX
        OPR_LEFT_RIGHT_MIXER "IN_1(1)"<-- "OUT_1(1)" OPR_USB_AUDIO_RX
        OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_LEFT_RIGHT_MIXER
        OPR_RATE_ADJUST "IN(0)"<-- "OUT(0)" OPR_SPEAKER_RESAMPLER
        OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_RATE_ADJUST
        OPR_SCO_SEND "IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_SCO_TO_AIR #lightblue
        EPR_SCO_TO_AIR <-- "SCO_OUT(0)" OPR_SCO_SEND
@enduml
@startuml inline_umlgraph_24.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_APTX_ADAPTIVE_ENCODER
        OPR_APTX_ADAPTIVE_ENCODER : id = CAP_ID_DOWNLOAD_APTX_ADAPTIVE_ENCODE
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_APTX_ADAPTIVE_ENCODER "IN_L(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_APTX_ADAPTIVE_ENCODER "IN_R(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_APTX_ADAPTIVE_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_25.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_APTX_ADAPTIVE_ENCODER
        OPR_APTX_ADAPTIVE_ENCODER : id = CAP_ID_APTX_ADAPTIVE_R3_ENCODE
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_APTX_ADAPTIVE_ENCODER "IN_L(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_APTX_ADAPTIVE_ENCODER "IN_R(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_APTX_ADAPTIVE_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_26.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_APTX_CLASSIC_ENCODER
        OPR_APTX_CLASSIC_ENCODER : id = CAP_ID_DOWNLOAD_APTX_CLASSIC_ENCODER
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_APTX_CLASSIC_ENCODER "IN_L(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_APTX_CLASSIC_ENCODER "IN_R(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_APTX_CLASSIC_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_27.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_APTXHD_ENCODER
        OPR_APTXHD_ENCODER : id = CAP_ID_DOWNLOAD_APTXHD_ENCODER
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_APTXHD_ENCODER "IN_L(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_APTXHD_ENCODER "IN_R(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_APTXHD_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
@startuml inline_umlgraph_28.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_LC3_ENCODE_SCO_ISO
        OPR_LC3_ENCODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_ENC
        object OPR_LC3_ENCODE_SCO_ISO_RIGHT
        OPR_LC3_ENCODE_SCO_ISO_RIGHT : id = CAP_ID_LC3_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_LC3_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_LC3_ENCODE_SCO_ISO_RIGHT "IN_R(0)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT_L(0)" OPR_LC3_ENCODE_SCO_ISO
        object EPR_ISO_TO_AIR_RIGHT #lightblue
        EPR_ISO_TO_AIR_RIGHT <-- "ISO_OUT_R(0)" OPR_LC3_ENCODE_SCO_ISO_RIGHT
@enduml
@startuml inline_umlgraph_29.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO
        OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO : id = CAP_ID_APTX_ADAPTIVE_SCO_ISO_ENC
        object OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO_RIGHT
        OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO_RIGHT : id = CAP_ID_APTX_ADAPTIVE_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO_RIGHT "IN_R(0)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT_L(0)" OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO
        object EPR_ISO_TO_AIR_RIGHT #lightblue
        EPR_ISO_TO_AIR_RIGHT <-- "ISO_OUT_R(0)" OPR_APTX_ADAPTIVE_ENCODE_SCO_ISO_RIGHT
@enduml
@startuml inline_umlgraph_30.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_APTX_LITE_ENCODE_SCO_ISO
        OPR_APTX_LITE_ENCODE_SCO_ISO : id = CAP_ID_APTX_LITE_SCO_ISO_ENC
        object OPR_APTX_LITE_ENCODE_SCO_ISO_RIGHT
        OPR_APTX_LITE_ENCODE_SCO_ISO_RIGHT : id = CAP_ID_APTX_LITE_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_APTX_LITE_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_LITE_ENCODE_SCO_ISO_RIGHT "IN_R(0)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT_L(0)" OPR_APTX_LITE_ENCODE_SCO_ISO
        object EPR_ISO_TO_AIR_RIGHT #lightblue
        EPR_ISO_TO_AIR_RIGHT <-- "ISO_OUT_R(0)" OPR_APTX_LITE_ENCODE_SCO_ISO_RIGHT
@enduml
@startuml inline_umlgraph_31.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_LC3_ENCODE_SCO_ISO
        OPR_LC3_ENCODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_LC3_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_LC3_ENCODE_SCO_ISO "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT(0)" OPR_LC3_ENCODE_SCO_ISO
@enduml
@startuml inline_umlgraph_32.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_APTX_LITE_ENCODE_SCO_ISO
        OPR_APTX_LITE_ENCODE_SCO_ISO : id = CAP_ID_APTX_LITE_SCO_ISO_ENC
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_SPEAKER_RESAMPLER "IN_1(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_APTX_LITE_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        OPR_APTX_LITE_ENCODE_SCO_ISO "IN_R(1)"<-- "OUT_1(1)" OPR_SPEAKER_RESAMPLER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT(0)" OPR_APTX_LITE_ENCODE_SCO_ISO
@enduml
@startuml inline_umlgraph_33.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_LEFT_RIGHT_MIXER
        OPR_LEFT_RIGHT_MIXER : id = CAP_ID_MIXER
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object OPR_LC3_ENCODE_SCO_ISO
        OPR_LC3_ENCODE_SCO_ISO : id = CAP_ID_LC3_SCO_ISO_ENC
        OPR_LEFT_RIGHT_MIXER "IN_0(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_LEFT_RIGHT_MIXER "IN_1(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_SPEAKER_RESAMPLER "IN_0(0)"<-- "OUT(0)" OPR_LEFT_RIGHT_MIXER
        OPR_LC3_ENCODE_SCO_ISO "IN_L(0)"<-- "OUT_0(0)" OPR_SPEAKER_RESAMPLER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_ISO_TO_AIR_LEFT #lightblue
        EPR_ISO_TO_AIR_LEFT <-- "ISO_OUT(0)" OPR_LC3_ENCODE_SCO_ISO
@enduml
@startuml inline_umlgraph_34.png
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object OPR_SBC_ENCODER
        OPR_SBC_ENCODER : id = CAP_ID_SBC_ENCODER
        object OPR_ENCODER_OUTPUT_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SBC_ENCODER "IN_L(0)"<-- "OUT_L(0)" OPR_LATENCY_BUFFER
        OPR_SBC_ENCODER "IN_R(1)"<-- "OUT_R(1)" OPR_LATENCY_BUFFER
        OPR_ENCODER_OUTPUT_BUFFER "IN(0)"<-- "OUT(0)" OPR_SBC_ENCODER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_ENCODER_OUTPUT_BUFFER
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_SOURCE_ENCODE_OUT #lightblue
        EPR_SOURCE_ENCODE_OUT <-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
@enduml
