/*!
\copyright  Copyright (c) 2021 Qualcomm Technologies International, Ltd.
            All Rights Reserved.
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\file
\ingroup    ml_example
\brief      Interface to machine learning kymera chain.

*/

#ifndef ML_H_
#define ML_H_

#include <source.h>
#include <message.h>

/*@{*/

/*! Model access methods */
typedef enum
{
    model_direct_access = 0,
    model_copy_and_auto_unload = 1,
    model_copy_and_manual_unload = 2
} model_access_methods_t ;

typedef struct
{
    uint16 use_case_id;
    uint16 capability_id;
    uint16 access_method;
    uint16 batch_reset_count;
    char *model_file;
    char *operator_bundle;
} ml_config_t;

/*! \brief Configure and start ML chain

    The output of this chain are messages sent to listener task.

    \param input     Data input
    \param listener  Task to which messages generated by ML chain will be sent
    \param ml_config Complete configuration of ML operators.

*/
void Ml_Start(Source input, Task listener, const ml_config_t *ml_config);

/*@}*/

#endif /* ML_H_ */
