/*!
    \copyright  Copyright (c) 2019 - 2023 Qualcomm Technologies International, Ltd.
                All Rights Reserved.
                Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version    
    \file       
    \ingroup    le_peer_pairing_service
    \brief      Constant data needed for the secret Peer pairing key.

    The Peer pairing secret key is generated by the host and compiled into
    the application.
*/

#include "peer_pair_le_key.h"
#ifdef USE_SYNERGY
#include <csr_bt_td_db.h>
#include <csr_bt_td_db_sc.h>
#include <csr_bt_td_db_gap.h>
#include <csr_bt_td_db_gatt.h>
#include <cm_lib.h>
#include <bdaddr.h>
#include <vm.h>
#include <panic.h>
#endif

const GRKS_KEY_T peer_pair_le_key = {
    {
        0x7b,     /* 00 */
        0x0e,     /* 01 */
        0x19,     /* 02 */
        0xc6,     /* 03 */
        0xd9,     /* 04 */
        0xb7,     /* 05 */
        0x4a,     /* 06 */
        0xcc,     /* 07 */
        0x99,     /* 08 */
        0x6d,     /* 09 */
        0x35,     /* 10 */
        0x61,     /* 11 */
        0xa9,     /* 12 */
        0x74,     /* 13 */
        0x5a,     /* 14 */
        0x7f      /* 15 */
    }
};

#ifdef USE_SYNERGY
bool peer_pair_le_duplicate_keys(const typed_bdaddr *origDevice,
                                 const typed_bdaddr *newDevice)
{
    CsrBtTypedAddr origDeviceAddr, newDeviceAddr;

    BdaddrConvertTypedVmToBluestack(&origDeviceAddr, origDevice);
    BdaddrConvertTypedVmToBluestack(&newDeviceAddr, newDevice);

    if (CsrBtTdDbDeviceExists(origDeviceAddr.type, &origDeviceAddr.addr))
    {
        CsrUint8 *buffer;
        CsrUint16 size = CSRMAX(sizeof(CsrBtCmKey), sizeof(CsrBtTdDbGattInfo));

        buffer = (CsrUint8 *) PanicUnlessMalloc(size);

        /* Duplicating BREDR key */
        if (CsrBtTdDbGetBredrKey(origDeviceAddr.type,
                                 &origDeviceAddr.addr,
                                 buffer) == CSR_BT_RESULT_CODE_TD_DB_SUCCESS)
        {
            /* To ensure that security keys are added in Bluestack */
            CmWriteBredrKeysReqSend(NULL,
                                    newDeviceAddr.type,
                                    &newDeviceAddr.addr,
                                    (CsrBtCmKey *) CsrMemDup(buffer,
                                                             sizeof(CsrBtTdDbBredrKey)));
        }

        /* Duplicating LE keys */
        if (CsrBtTdDbGetLeKeys(origDeviceAddr.type,
                               &origDeviceAddr.addr,
                               buffer) == CSR_BT_RESULT_CODE_TD_DB_SUCCESS)
        {
            /* To ensure that security keys are added in Bluestack */
            CmWriteLeKeysReqSend(NULL,
                                 newDeviceAddr.type,
                                 &newDeviceAddr.addr,
                                 (CsrBtCmKey *) CsrMemDup(buffer,
                                                          sizeof(CsrBtTdDbLeKeys)));
        }

        /* Duplicating gatt information */
        if (CsrBtTdDbGetGattInfo(origDeviceAddr.type,
                                 &origDeviceAddr.addr,
                                 buffer) == CSR_BT_RESULT_CODE_TD_DB_SUCCESS)
        {
            CsrBtTdDbSetGattInfo(newDeviceAddr.type,
                                 &newDeviceAddr.addr,
                                 buffer);
        }
        
        /* Duplicating direct key */
        if (CsrBtTdDbReadEntry(origDeviceAddr.type,
                               &origDeviceAddr.addr,
                               CSR_BT_TD_DB_SOURCE_DIRECT,
                               CSR_BT_TD_DB_DIRECT_KEY_ATTR,
                               &size,
                               NULL) == CSR_BT_RESULT_CODE_TD_DB_SUCCESS)
        {
            pfree(buffer);
            buffer = (CsrUint8 *) PanicUnlessMalloc(size);

            (void) CsrBtTdDbGetEntry(origDeviceAddr.type,
                                     &origDeviceAddr.addr,
                                     CSR_BT_TD_DB_SOURCE_DIRECT,
                                     CSR_BT_TD_DB_DIRECT_KEY_ATTR,
                                     size,
                                     buffer);

            CsrBtTdDbWriteEntry(newDeviceAddr.type,
                                &newDeviceAddr.addr,
                                CSR_BT_TD_DB_SOURCE_DIRECT,
                                CSR_BT_TD_DB_DIRECT_KEY_ATTR,
                                size,
                                buffer);
        }

        pfree(buffer);
        return TRUE;
    }

    return FALSE;
}
#endif
