#ifndef _BAP_CLIENT_ASE_FSM_DEFINITIONS_H
#define _BAP_CLIENT_ASE_FSM_DEFINITIONS_H
/*!
 Copyright (c) 2010-2023 Qualcomm Technologies International, Ltd.
 All Rights Reserved.
 Qualcomm Technologies International, Ltd. Confidential and Proprietary.

\file   bap_client_ase_fsm_definitions.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version 2D
*/

#include "fsm.h"

#ifdef __cplusplus
extern "C" {
#endif
#ifdef INSTALL_LEA_UNICAST_CLIENT

/* Action function prototypes */
/*{{__FSM_MARKER(BapClientAse, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(bapClientAseAfSendConfigCodecOp);
extern FSM_ACTION_FN(bapClientAseAfCodecConfigureIndReceived);
extern FSM_ACTION_FN(bapClientAseAfCodecConfigureCfmReceived);
extern FSM_ACTION_FN(bapClientAseAfCodecConfigureCfmFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfSendReleaseOp);
extern FSM_ACTION_FN(bapClientAseAfReleaseCfmReceived);
extern FSM_ACTION_FN(bapClientAseAfSendConfigQosOp);
extern FSM_ACTION_FN(bapClientAseAfReleaseIndReceived);
extern FSM_ACTION_FN(bapClientAseAfQosConfigureCfmReceived);
extern FSM_ACTION_FN(bapClientAseAfQosConfigureCfmFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfSendEnableOp);
extern FSM_ACTION_FN(bapClientAseAfSendCisDisconnect);
extern FSM_ACTION_FN(bapClientAseAfCisDisconnectReceived);
extern FSM_ACTION_FN(bapClientAseAfCisDisconnectIndReceived);
extern FSM_ACTION_FN(bapClientAseAfCisConnect);
extern FSM_ACTION_FN(bapClientAseAfCisConnectCfmSuccessReceived);
extern FSM_ACTION_FN(bapClientAseAfCisConnectCfmFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfDisableIndReceived);
extern FSM_ACTION_FN(bapClientAseAfEnableCfmReceived);
extern FSM_ACTION_FN(bapClientAseAfEnableFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfSendDisableOp);
extern FSM_ACTION_FN(bapClientAseAfSendUpdateMetadataOp);
extern FSM_ACTION_FN(bapClientAseAfUpdateMetadataCfmReceived);
extern FSM_ACTION_FN(bapClientAseAfUpdateMetadataFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfStopReadyCfmReceived);
extern FSM_ACTION_FN(bapClientAseAfSendStartReadyOp);
extern FSM_ACTION_FN(bapClientAseAfStartReadyReceived);
extern FSM_ACTION_FN(bapClientAseAfStartReadyFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfStopReadySendOp);
extern FSM_ACTION_FN(bapClientAseAfStopReadyCfmFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfDisableCfmReceived);
extern FSM_ACTION_FN(bapClientAseAfDisableCfmFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfReleaseCfmFailedReceived);
extern FSM_ACTION_FN(bapClientAseAfReleasedIndReceived);
/*}}__FSM_END_MARKER(BapClientAse, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(BapClientAse, STATE_DECLARATIONS) */
#define CLIENT_ASE_STATE_ST_MAX 22
#define CLIENT_ASE_STATE_IDLE                                 ((fsm_state_t) 0)
#define CLIENT_ASE_STATE_WAIT_CODEC_CONFIGURE_CFM             ((fsm_state_t) 1)
#define CLIENT_ASE_STATE_CODEC_CONFIGURED                     ((fsm_state_t) 2)
#define CLIENT_ASE_STATE_WAIT_QOS_CONFIGURE_CFM               ((fsm_state_t) 3)
#define CLIENT_ASE_STATE_QOS_CONFIGURED                       ((fsm_state_t) 4)
#define CLIENT_ASE_STATE_WAIT_CIS_DISCONNECT_CFM              ((fsm_state_t) 5)
#define CLIENT_ASE_STATE_WAIT_QOS_CIS_CONNECT_CFM             ((fsm_state_t) 6)
#define CLIENT_ASE_STATE_RECONFIGURE_WAIT_CODEC_CONFIGURE_CFM ((fsm_state_t) 7)
#define CLIENT_ASE_STATE_WAIT_ENABLE_CFM                      ((fsm_state_t) 8)
#define CLIENT_ASE_STATE_QOS_CIS_CONNECTED                    ((fsm_state_t) 9)
#define CLIENT_ASE_STATE_WAIT_QOS_CIS_ENABLE_CFM              ((fsm_state_t) 10)
#define CLIENT_ASE_STATE_WAIT_QOS_CIS_DISCONNECT_CFM          ((fsm_state_t) 11)
#define CLIENT_ASE_STATE_ENABLING                             ((fsm_state_t) 12)
#define CLIENT_ASE_STATE_WAIT_CIS_CONNECT_CFM                 ((fsm_state_t) 13)
#define CLIENT_ASE_STATE_CIS_CONNECTED                        ((fsm_state_t) 14)
#define CLIENT_ASE_STATE_WAIT_START_READY_CFM                 ((fsm_state_t) 15)
#define CLIENT_ASE_STATE_STREAMING                            ((fsm_state_t) 16)
#define CLIENT_ASE_STATE_DISABLING                            ((fsm_state_t) 17)
#define CLIENT_ASE_STATE_WAIT_STOP_READY_CFM                  ((fsm_state_t) 18)
#define CLIENT_ASE_STATE_WAIT_DISABLE_CFM                     ((fsm_state_t) 19)
#define CLIENT_ASE_STATE_WAIT_RELEASE_CFM                     ((fsm_state_t) 20)
#define CLIENT_ASE_STATE_RELEASING                            ((fsm_state_t) 21)
/*}}__FSM_END_MARKER(BapClientAse, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(BapClientAse, EVENT_DECLARATIONS) */
#define CLIENT_ASE_EVENT_CONFIGURE                    ((fsm_event_t) 0)
#define CLIENT_ASE_EVENT_CONFIGURE_IND                ((fsm_event_t) 1)
#define CLIENT_ASE_EVENT_CODEC_CONFIGURE_CFM_RECEIVED ((fsm_event_t) 2)
#define CLIENT_ASE_EVENT_FAILED_CFM_RECEIVED          ((fsm_event_t) 3)
#define CLIENT_ASE_EVENT_RELEASE                      ((fsm_event_t) 4)
#define CLIENT_ASE_EVENT_RELEASE_CFM_RECEIVED         ((fsm_event_t) 5)
#define CLIENT_ASE_EVENT_QOS_CONFIGURE                ((fsm_event_t) 6)
#define CLIENT_ASE_EVENT_RELEASE_IND                  ((fsm_event_t) 7)
#define CLIENT_ASE_EVENT_QOS_CONFIGURE_CFM_RECEIVED   ((fsm_event_t) 8)
#define CLIENT_ASE_EVENT_ENABLE                       ((fsm_event_t) 9)
#define CLIENT_ASE_EVENT_CIS_DISCONNECT               ((fsm_event_t) 10)
#define CLIENT_ASE_EVENT_CIS_DISCONNECT_CFM_RECEIVED  ((fsm_event_t) 11)
#define CLIENT_ASE_EVENT_CIS_DISCONNECT_IND           ((fsm_event_t) 12)
#define CLIENT_ASE_EVENT_CIS_CONNECT                  ((fsm_event_t) 13)
#define CLIENT_ASE_EVENT_CIS_ESTABLISHED              ((fsm_event_t) 14)
#define CLIENT_ASE_EVENT_CIS_FAILED                   ((fsm_event_t) 15)
#define CLIENT_ASE_EVENT_DISABLE_IND                  ((fsm_event_t) 16)
#define CLIENT_ASE_EVENT_ENABLE_CFM_RECEIVED          ((fsm_event_t) 17)
#define CLIENT_ASE_EVENT_DISABLE                      ((fsm_event_t) 18)
#define CLIENT_ASE_EVENT_UPDATE_METADATA              ((fsm_event_t) 19)
#define CLIENT_ASE_EVENT_METADATA_CFM_RECEIVED        ((fsm_event_t) 20)
#define CLIENT_ASE_EVENT_STOP_READY_RECEIVED          ((fsm_event_t) 21)
#define CLIENT_ASE_EVENT_START_READY                  ((fsm_event_t) 22)
#define CLIENT_ASE_EVENT_START_READY_RECEIVED         ((fsm_event_t) 23)
#define CLIENT_ASE_EVENT_STOP_READY_SEND              ((fsm_event_t) 24)
#define CLIENT_ASE_EVENT_DISABLE_CFM_RECEIVED         ((fsm_event_t) 25)
#define CLIENT_ASE_EVENT_RELEASED_IND_RECEIVED        ((fsm_event_t) 26)
#define CLIENT_ASE_EVENT_RELEASED_RECEIVED            ((fsm_event_t) 27)
/*}}__FSM_END_MARKER(BapClientAse, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(BapClientAse, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(BapClientAse, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(BapClientAse, ACTION_FN_INDEX) */
#define CLIENT_ASE_AC_MAX 34
#define CLIENT_ASE_AC_send_config_codec_op                ((fsm_action_t) 0)
#define CLIENT_ASE_AC_codec_configure_ind_received        ((fsm_action_t) 1)
#define CLIENT_ASE_AC_codec_configure_cfm_received        ((fsm_action_t) 2)
#define CLIENT_ASE_AC_codec_configure_cfm_failed_received ((fsm_action_t) 3)
#define CLIENT_ASE_AC_send_release_op                     ((fsm_action_t) 4)
#define CLIENT_ASE_AC_release_cfm_received                ((fsm_action_t) 5)
#define CLIENT_ASE_AC_send_config_qos_op                  ((fsm_action_t) 6)
#define CLIENT_ASE_AC_release_ind_received                ((fsm_action_t) 7)
#define CLIENT_ASE_AC_qos_configure_cfm_received          ((fsm_action_t) 8)
#define CLIENT_ASE_AC_qos_configure_cfm_failed_received   ((fsm_action_t) 9)
#define CLIENT_ASE_AC_send_enable_op                      ((fsm_action_t) 10)
#define CLIENT_ASE_AC_send_cis_disconnect                 ((fsm_action_t) 11)
#define CLIENT_ASE_AC_cis_disconnect_received             ((fsm_action_t) 12)
#define CLIENT_ASE_AC_cis_disconnect_ind_received         ((fsm_action_t) 13)
#define CLIENT_ASE_AC_cis_connect                         ((fsm_action_t) 14)
#define CLIENT_ASE_AC_cis_connect_cfm_success_received    ((fsm_action_t) 15)
#define CLIENT_ASE_AC_cis_connect_cfm_failed_received     ((fsm_action_t) 16)
#define CLIENT_ASE_AC_disable_ind_received                ((fsm_action_t) 17)
#define CLIENT_ASE_AC_enable_cfm_received                 ((fsm_action_t) 18)
#define CLIENT_ASE_AC_enable_failed_received              ((fsm_action_t) 19)
#define CLIENT_ASE_AC_send_disable_op                     ((fsm_action_t) 20)
#define CLIENT_ASE_AC_send_update_metadata_op             ((fsm_action_t) 21)
#define CLIENT_ASE_AC_update_metadata_cfm_received        ((fsm_action_t) 22)
#define CLIENT_ASE_AC_update_metadata_failed_received     ((fsm_action_t) 23)
#define CLIENT_ASE_AC_stop_ready_cfm_received             ((fsm_action_t) 24)
#define CLIENT_ASE_AC_send_start_ready_op                 ((fsm_action_t) 25)
#define CLIENT_ASE_AC_start_ready_received                ((fsm_action_t) 26)
#define CLIENT_ASE_AC_start_ready_failed_received         ((fsm_action_t) 27)
#define CLIENT_ASE_AC_stop_ready_send_op                  ((fsm_action_t) 28)
#define CLIENT_ASE_AC_stop_ready_cfm_failed_received      ((fsm_action_t) 29)
#define CLIENT_ASE_AC_disable_cfm_received                ((fsm_action_t) 30)
#define CLIENT_ASE_AC_disable_cfm_failed_received         ((fsm_action_t) 31)
#define CLIENT_ASE_AC_release_cfm_failed_received         ((fsm_action_t) 32)
#define CLIENT_ASE_AC_released_ind_received               ((fsm_action_t) 33)
#define CLIENT_ASE_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(BapClientAse, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(BapClientAse, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T bapClientAseFsm;
/*}}__FSM_END_MARKER(BapClientAse, FSM_DEFINITION) */

#endif /*#ifdef INSTALL_LEA_UNICAST_CLIENT */

#ifdef __cplusplus
}
#endif

#endif /* _BAP_CLIENT_ASE_FSM_DEFINITIONS_H */

