// -----------------------------------------------------------------------------
// Copyright (c) 2023                  Qualcomm Technologies International, Ltd.
//
// Generated by /home/svc-audio-dspsw/kymera_builds/builds/2023/kymera_2312060823/kalimba/kymera/../../util/CommonParameters/DerivationEngine.py
// code v3.5, file //depot/dspsw/maor_rom_v20/util/CommonParameters/DerivationEngine.py, revision 2
// namespace {com.csr.cps.4}UnifiedParameterSchema on 2023-12-06 08:58:22 by svc-audio-dspsw
//
// input from EMPTY
// last change  by  on 
// -----------------------------------------------------------------------------
#include "atr_vad_gen_c.h"

#ifndef __GNUC__ 
_Pragma("datasection CONST")
#endif /* __GNUC__ */

static unsigned defaults_atr_vadATR_VAD[] = {
   0x00000000u,			// ATR_VAD_CONFIG
   0x00CCCCCDu,			// VAD_ATTACK_TIME
   0x00CCCCCDu,			// VAD_RELEASE_TIME
   0x00049BA6u,			// VAD_ENVELOPE_TIME
   0x53333333u,			// VAD_RATIO
   0x00041893u,			// VAD_INIT_TIME
   0xFB000000u,			// VAD_PWR_THRESHOLD
   0x00A00000u,			// VAD_ENV_THRESHOLD
   0x00200000u,			// VAD_DELTA_THRESHOLD
   0x01F33333u,			// VAD_COUNT_TH_TIME
   0x00666666u,			// SMOOTH_ATTACK_TIME
   0x00CCCCCDu,			// SMOOTH_RELEASE_TIME
   0x0000199Au,			// HOLD_ATTACK_TIME
   0x0001999Au,			// HOLD_RELEASE_TIME
   0x3999999Au,			// DET_THRESHOLD
   0x000A0000u,			// MSG_SHORT_RELEASE_TIME
   0x00140000u,			// MSG_NORMAL_RELEASE_TIME
   0x001E0000u,			// MSG_LONG_RELEASE_TIME
   0x00010000u			// MSG_ATTACK_TIME
};

unsigned *ATR_VAD_GetDefaults(unsigned capid){
	switch(capid){
		case 0x00E3: return defaults_atr_vadATR_VAD;
		case 0x40C9: return defaults_atr_vadATR_VAD;
	}
	return((unsigned *)0);
}
