#-*-Makefile-*-
###############################################################################
# Copyright (c) 2008-2017 Qualcomm Technologies International, Ltd.
# All Rights Reserved.
# Qualcomm Technologies International, Ltd. Confidential and Proprietary.
#
# REVISION:      $Revision: #1 $
###############################################################################
TOP := ../../../..

OBJ_PATH = $(TOP)/output/$(CONFIG)/$(TARGET)/obj/src/hid/device/code

include $(TOP)/local_rules.mk

MODULE_NAME := hidd

include $(TOP)/profile_managers/pm.mk

