// -----------------------------------------------------------------------------
// Copyright (c) 2023                  Qualcomm Technologies International, Ltd.
//
// Generated by /home/svc-audio-dspsw/kymera_builds/builds/2023/kymera_2312060823/kalimba/kymera/../../util/CommonParameters/DerivationEngine.py
// code v3.5, file //depot/dspsw/maor_rom_v20/util/CommonParameters/DerivationEngine.py, revision 2
// namespace {com.csr.cps.4}UnifiedParameterSchema on 2023-12-06 08:54:53 by svc-audio-dspsw
//
// input from EMPTY
// last change  by  on 
// -----------------------------------------------------------------------------
#include "wind_noise_detect_gen_c.h"

#ifndef __GNUC__ 
_Pragma("datasection CONST")
#endif /* __GNUC__ */

static unsigned defaults_wind_noise_detectWIND_NOISE_DETECT[] = {
   0x00000000u,			// WND_CONFIG
   0x00CAC083u,			// 1MIC_FILTER_ATTACK
   0x00CAC083u,			// 1MIC_FILTER_DECAY
   0x40000000u,			// 1MIC_THRESHOLD
   0x00200000u,			// 1MIC_MESSAGE_ATTACK
   0x00100000u,			// 1MIC_MESSAGE_RELEASE
   0x007FBE77u,			// 2MIC_FILTER_ATTACK
   0x009205BCu,			// 2MIC_FILTER_DECAY
   0x05C28F5Cu,			// 2MIC_THRESHOLD
   0x00200000u,			// 2MIC_MESSAGE_ATTACK
   0x00100000u,			// 2MIC_MESSAGE_RELEASE
   0x0083126Fu,			// POWER_THRESHOLD
   0x07FEF9DBu,			// POWER_ENVELOPE_TIME
   0x02A9A027u,			// POWER_ATTACK_TIME
   0xFCC00000u,			// MED_WIND_THRESHOLD
   0xFD600000u,			// HIGH_WIND_THRESHOLD
   0xFC700000u,			// MED_REL_WIND_THRESHOLD
   0xFD100000u,			// HIGH_REL_WIND_THRESHOLD
   0x0001999Au,			// LOW_WIND_FF_RAMP_DURATION
   0x0001999Au,			// LOW_WIND_FB_RAMP_DURATION
   0x8000FF00u,			// LOW_WIND_FF_FINE_GAIN
   0x80000000u,			// LOW_WIND_FB_FINE_GAIN
   0x0001999Au,			// MEDIUM_WIND_FF_RAMP_DURATION
   0x0001999Au,			// MEDIUM_WIND_FB_RAMP_DURATION
   0x8000FE00u,			// MEDIUM_WIND_FF_FINE_GAIN
   0x80000000u,			// MEDIUM_WIND_FB_FINE_GAIN
   0x0001999Au,			// HIGH_WIND_FF_RAMP_DURATION
   0x0001999Au,			// HIGH_WIND_FB_RAMP_DURATION
   0x8000FD00u,			// HIGH_WIND_FF_FINE_GAIN
   0x80000000u			// HIGH_WIND_FB_FINE_GAIN
};

unsigned *WIND_NOISE_DETECT_GetDefaults(unsigned capid){
	switch(capid){
		case 0x00DF: return defaults_wind_noise_detectWIND_NOISE_DETECT;
		case 0x40C0: return defaults_wind_noise_detectWIND_NOISE_DETECT;
	}
	return((unsigned *)0);
}
