/*!
\copyright  Copyright (c) 2021 - 2023 Qualcomm Technologies International, Ltd.\n
            All Rights Reserved.\n
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\file
\brief      Definitions of audio capability IDs
*/

#ifndef USB_DONGLE_CAP_IDS_H
#define USB_DONGLE_CAP_IDS_H

#if defined(__QCC307X__) || defined(__QCC517X__)
#ifdef INCLUDE_SOURCE_APP_LE_AUDIO
#define DOWNLOAD_LC3_ENCODE_SCO_ISO
#define DOWNLOAD_LC3_DECODE_SCO_ISO
#endif /* INCLUDE_SOURCE_APP_LE_AUDIO */

#ifdef INCLUDE_APTX_ADAPTIVE_22
/* AptX Adaptive R2.2 is supported in Kernel R3.0 */
#define DOWNLOAD_APTX_ADAPTIVE_R3
#endif /* INCLUDE_APTX_ADAPTIVE_22 */
#endif

#ifdef INCLUDE_LE_AUDIO_GAMING_MODE_APTX_LITE
#define DOWNLOAD_APTX_LITE_ENCODE_SCO_ISO
#define DOWNLOAD_APTX_LITE_DECODE_SCO_ISO
#endif

#ifdef INCLUDE_LE_APTX_ADAPTIVE
#define DOWNLOAD_APTX_ADAPTIVE_ENCODE_SCO_ISO
#endif

#ifdef DOWNLOAD_SWBS_ENC_DEC
#define UD_CAP_ID_SWBS_ENC CAP_ID_DOWNLOAD_SWBS_ENC
#define UD_CAP_ID_SWBS_DEC CAP_ID_DOWNLOAD_SWBS_DEC
#else
#define UD_CAP_ID_SWBS_ENC CAP_ID_SWBS_ENC
#define UD_CAP_ID_SWBS_DEC CAP_ID_SWBS_DEC
#endif

#ifdef DOWNLOAD_LC3_ENCODE_SCO_ISO
#define CAP_ID_LC3_SCO_ISO_ENC    0x409A /* CAP_ID_DOWNLOAD_LC3_ENCODE_SCO_ISO */
#else
#define CAP_ID_LC3_SCO_ISO_ENC    0X00C4 /*CAP_ID_LC3_ENCODE_SCO_ISO */
#endif

#ifdef DOWNLOAD_LC3_DECODE_SCO_ISO
#define CAP_ID_LC3_SCO_ISO_DEC 0x4098 /*CAP_ID_DOWNLOAD_LC3_DECODE_SCO_ISO*/
#else
#define CAP_ID_LC3_SCO_ISO_DEC 0x00C2 /*CAP_ID_LC3_DECODE_SCO_ISO*/
#endif

#ifdef DOWNLOAD_APTX_LITE_ENCODE_SCO_ISO
#define CAP_ID_APTX_LITE_SCO_ISO_ENC    0x40D5 /* CAP_ID_DOWNLOAD_APTX_LITE_ENCODE_SCO_ISO */
#else
#define CAP_ID_APTX_LITE_SCO_ISO_ENC    CAP_ID_NONE
#endif

#ifdef DOWNLOAD_APTX_ADAPTIVE_ENCODE_SCO_ISO
#define CAP_ID_APTX_ADAPTIVE_SCO_ISO_ENC    0x40DE
#else
#define CAP_ID_APTX_ADAPTIVE_SCO_ISO_ENC    CAP_ID_NONE
#endif

#ifdef DOWNLOAD_APTX_LITE_DECODE_SCO_ISO
#define CAP_ID_APTX_LITE_SCO_ISO_DEC 0x40D6 /*CAP_ID_DOWNLOAD_APTX_LITE_DECODE_SCO_ISO*/
#else
#define CAP_ID_APTX_LITE_SCO_ISO_DEC CAP_ID_NONE
#endif

#ifdef DOWNLOAD_APTX_ADAPTIVE_R3
#define CAP_ID_APTX_ADAPTIVE_R3_ENCODE 0x40BD /*CAP_ID_DOWNLOAD_APTX_ADAPTIVE_R3_ENCODE*/
#else
#define CAP_ID_APTX_ADAPTIVE_R3_ENCODE CAP_ID_NONE
#endif

#endif // USB_DONGLE_CAP_IDS_H

