@startuml inline_umlgraph_1.png
    note "Charger Case Application States" as N1
   
    [*] -down-> CHARGERCASE_STATE_NULL: HS State Init
    CHARGERCASE_STATE_NULL -down->CHARGERCASE_STATE_LIMBO :SSM transition to system_state_limbo
    CHARGERCASE_STATE_NULL: Initial state
    state ChargerCaseisactive {
        CHARGERCASE_STATE_LIMBO->CHARGERCASE_STATE_LIMBO: Start Limbo Timer
        CHARGERCASE_STATE_LIMBO: Stable state after Startup
        CHARGERCASE_STATE_LIMBO->CHARGERCASE_STATE_POWERING_ON:User Initiated Power On/SSM transition to system_state_powering_on
        CHARGERCASE_STATE_POWERING_ON-down->CHARGERCASE_STATE_IDLE: If already a device in PDL
        CHARGERCASE_STATE_IDLE:Can have BT connection or not
        CHARGERCASE_STATE_POWERING_ON -down-> CHARGERCASE_STATE_PAIRING: If no device in PDL
        CHARGERCASE_STATE_POWERING_ON : A transition state for powering On
        CHARGERCASE_STATE_PAIRING -> CHARGERCASE_STATE_IDLE: If pairing successful or failed
        CHARGERCASE_STATE_IDLE-down->CHARGERCASE_STATE_BUSY:Start Music Streaming/Call(BT)
        CHARGERCASE_STATE_IDLE-left->CHARGERCASE_STATE_IDLE:Start Idle timer in case of no activity(eg:No BT)
        CHARGERCASE_STATE_IDLE->CHARGERCASE_STATE_PAIRING:User Initiated Pairing
    }
    CHARGERCASE_STATE_IDLE-up->CHARGERCASE_STATE_POWERING_OFF:Idle Timer Expires and Ok to power off(eg:No BT)
    CHARGERCASE_STATE_BUSY->CHARGERCASE_STATE_IDLE:End Music Streaming/Call
    ChargerCaseisactive -up->CHARGERCASE_STATE_POWERING_OFF: User Initiated Power OFF
    ChargerCaseisactive -up->CHARGERCASE_STATE_TERMINATING : Emergency Shutdown
    CHARGERCASE_STATE_TERMINATING: State to handle Emergency Shutdown
    CHARGERCASE_STATE_TERMINATING->PowerdOff
    CHARGERCASE_STATE_POWERING_OFF ->CHARGERCASE_STATE_POWERING_OFF: Disconnect Link if needed
    CHARGERCASE_STATE_POWERING_OFF: State to handle normal PowerOFF
    CHARGERCASE_STATE_POWERING_OFF ->CHARGERCASE_STATE_LIMBO
    CHARGERCASE_STATE_LIMBO -left->PowerdOff:No ChargerConnected/Limbo Timer Expires
    state PowerdOff #LightBlue
    PowerdOff: This state is realized in hardware, either Dormant or Off
    note left of CHARGERCASE_STATE_LIMBO
        A Limbo timer and Charger 
        determines the transition
        to PowerdOff
        If Charger is connected
        Charger Case will be in Limbo
        Else after Limbo timer 
        expires state transition
        to PowerdOff
    end note
    state CHARGERCASE_FACTORY_RESET:Reset the system, Can be entered after Power On
    CHARGERCASE_FACTORY_RESET-left->[*]
@enduml
@startuml inline_umlgraph_2.png
    note "Charger Case Application States" as N1
   
    [*] -down-> CHARGERCASE_STATE_NULL: HS State Init
    CHARGERCASE_STATE_NULL -down->CHARGERCASE_STATE_LIMBO :SSM transition to system_state_limbo
    CHARGERCASE_STATE_NULL: Initial state
    state ChargerCaseisactive {
        CHARGERCASE_STATE_LIMBO->CHARGERCASE_STATE_LIMBO: Start Limbo Timer
        CHARGERCASE_STATE_LIMBO: Stable state after Startup
        CHARGERCASE_STATE_LIMBO->CHARGERCASE_STATE_POWERING_ON:User Initiated Power On/SSM transition to system_state_powering_on
        CHARGERCASE_STATE_POWERING_ON-down->CHARGERCASE_STATE_IDLE: If already a device in PDL
        CHARGERCASE_STATE_IDLE:Can have BT connection or not
        CHARGERCASE_STATE_POWERING_ON -down-> CHARGERCASE_STATE_PAIRING: If no device in PDL
        CHARGERCASE_STATE_POWERING_ON : A transition state for powering On
        CHARGERCASE_STATE_PAIRING -> CHARGERCASE_STATE_IDLE: If pairing successful or failed
        CHARGERCASE_STATE_IDLE-down->CHARGERCASE_STATE_BUSY:Start Music Streaming/Call(BT)
        CHARGERCASE_STATE_IDLE-left->CHARGERCASE_STATE_IDLE:Start Idle timer in case of no activity(eg:No BT)
        CHARGERCASE_STATE_IDLE->CHARGERCASE_STATE_PAIRING:User Initiated Pairing
    }
    CHARGERCASE_STATE_IDLE-up->CHARGERCASE_STATE_POWERING_OFF:Idle Timer Expires and Ok to power off(eg:No BT)
    CHARGERCASE_STATE_BUSY->CHARGERCASE_STATE_IDLE:End Music Streaming/Call
    ChargerCaseisactive -up->CHARGERCASE_STATE_POWERING_OFF: User Initiated Power OFF
    ChargerCaseisactive -up->CHARGERCASE_STATE_TERMINATING : Emergency Shutdown
    CHARGERCASE_STATE_TERMINATING: State to handle Emergency Shutdown
    CHARGERCASE_STATE_TERMINATING->PowerdOff
    CHARGERCASE_STATE_POWERING_OFF ->CHARGERCASE_STATE_POWERING_OFF: Disconnect Link if needed
    CHARGERCASE_STATE_POWERING_OFF: State to handle normal PowerOFF
    CHARGERCASE_STATE_POWERING_OFF ->CHARGERCASE_STATE_LIMBO
    CHARGERCASE_STATE_LIMBO -left->PowerdOff:No ChargerConnected/Limbo Timer Expires
    state PowerdOff #LightBlue
    PowerdOff: This state is realized in hardware, either Dormant or Off
    note left of CHARGERCASE_STATE_LIMBO
        A Limbo timer and Charger 
        determines the transition
        to PowerdOff
        If Charger is connected
        Charger Case will be in Limbo
        Else after Limbo timer 
        expires state transition
        to PowerdOff
    end note
    state CHARGERCASE_FACTORY_RESET:Reset the system, Can be entered after Power On
    CHARGERCASE_FACTORY_RESET-left->[*]
@enduml
