@startuml inline_umlgraph_1.png
    note "Headset Application States" as N1
   
    [*] -down-> HEADSET_STATE_NULL: HS State Init
    HEADSET_STATE_NULL -down->HEADSET_STATE_LIMBO :SSM transition to system_state_limbo
    HEADSET_STATE_NULL: Initial state
    state Headsetisactive {
        HEADSET_STATE_LIMBO->HEADSET_STATE_LIMBO: Start Limbo Timer
        HEADSET_STATE_LIMBO: Stable state after Startup
        HEADSET_STATE_LIMBO->HEADSET_STATE_POWERING_ON:User Initiated Power On/SSM transition to system_state_powering_on
        HEADSET_STATE_POWERING_ON-down->HEADSET_STATE_IDLE: If already a device in PDL
        HEADSET_STATE_IDLE:Can have BT connection or not
        HEADSET_STATE_POWERING_ON -down-> HEADSET_STATE_PAIRING: If no device in PDL
        HEADSET_STATE_POWERING_ON : A transition state for powering On
        HEADSET_STATE_PAIRING -> HEADSET_STATE_IDLE: If pairing successful or failed
        HEADSET_STATE_IDLE-down->HEADSET_STATE_BUSY:Start Music Streaming/Call(BT)
        HEADSET_STATE_IDLE-left->HEADSET_STATE_IDLE:Start Idle timer in case of no activity(eg:No BT)
        HEADSET_STATE_IDLE->HEADSET_STATE_PAIRING:User Initiated Pairing
    }
    HEADSET_STATE_IDLE-up->HEADSET_STATE_POWERING_OFF:Idle Timer Expires and Ok to power off(eg:No BT)
    HEADSET_STATE_BUSY->HEADSET_STATE_IDLE:End Music Streaming/Call
    Headsetisactive -up->HEADSET_STATE_POWERING_OFF: User Initiated Power OFF
    Headsetisactive -up->HEADSET_STATE_TERMINATING : Emergency Shutdown
    HEADSET_STATE_TERMINATING: State to handle Emergency Shutdown
    HEADSET_STATE_TERMINATING->PowerdOff
    HEADSET_STATE_POWERING_OFF ->HEADSET_STATE_POWERING_OFF: Disconnect Link if needed
    HEADSET_STATE_POWERING_OFF: State to handle normal PowerOFF
    HEADSET_STATE_POWERING_OFF ->HEADSET_STATE_LIMBO 
    HEADSET_STATE_LIMBO -left->PowerdOff:No ChargerConnected/Limbo Timer Expires 
    state PowerdOff #LightBlue
    PowerdOff: This state is realized in hardware, either Dormant or Off
    note left of HEADSET_STATE_LIMBO
        A Limbo timer and Charger 
        determines the transition
        to PowerdOff
        If Charger is connected
        Headset will be in Limbo
        Else after Limbo timer 
        expires state transition
        to PowerdOff
    end note
    state HEADSET_FACTORY_RESET:Reset the system, Can be entered after Power On
    HEADSET_FACTORY_RESET-left->[*]
@enduml
@startuml inline_umlgraph_2.png
    note "Headset Application States" as N1
   
    [*] -down-> HEADSET_STATE_NULL: HS State Init
    HEADSET_STATE_NULL -down->HEADSET_STATE_LIMBO :SSM transition to system_state_limbo
    HEADSET_STATE_NULL: Initial state
    state Headsetisactive {
        HEADSET_STATE_LIMBO->HEADSET_STATE_LIMBO: Start Limbo Timer
        HEADSET_STATE_LIMBO: Stable state after Startup
        HEADSET_STATE_LIMBO->HEADSET_STATE_POWERING_ON:User Initiated Power On/SSM transition to system_state_powering_on
        HEADSET_STATE_POWERING_ON-down->HEADSET_STATE_IDLE: If already a device in PDL
        HEADSET_STATE_IDLE:Can have BT connection or not
        HEADSET_STATE_POWERING_ON -down-> HEADSET_STATE_PAIRING: If no device in PDL
        HEADSET_STATE_POWERING_ON : A transition state for powering On
        HEADSET_STATE_PAIRING -> HEADSET_STATE_IDLE: If pairing successful or failed
        HEADSET_STATE_IDLE-down->HEADSET_STATE_BUSY:Start Music Streaming/Call(BT)
        HEADSET_STATE_IDLE-left->HEADSET_STATE_IDLE:Start Idle timer in case of no activity(eg:No BT)
        HEADSET_STATE_IDLE->HEADSET_STATE_PAIRING:User Initiated Pairing
    }
    HEADSET_STATE_IDLE-up->HEADSET_STATE_POWERING_OFF:Idle Timer Expires and Ok to power off(eg:No BT)
    HEADSET_STATE_BUSY->HEADSET_STATE_IDLE:End Music Streaming/Call
    Headsetisactive -up->HEADSET_STATE_POWERING_OFF: User Initiated Power OFF
    Headsetisactive -up->HEADSET_STATE_TERMINATING : Emergency Shutdown
    HEADSET_STATE_TERMINATING: State to handle Emergency Shutdown
    HEADSET_STATE_TERMINATING->PowerdOff
    HEADSET_STATE_POWERING_OFF ->HEADSET_STATE_POWERING_OFF: Disconnect Link if needed
    HEADSET_STATE_POWERING_OFF: State to handle normal PowerOFF
    HEADSET_STATE_POWERING_OFF ->HEADSET_STATE_LIMBO 
    HEADSET_STATE_LIMBO -left->PowerdOff:No ChargerConnected/Limbo Timer Expires 
    state PowerdOff #LightBlue
    PowerdOff: This state is realized in hardware, either Dormant or Off
    note left of HEADSET_STATE_LIMBO
        A Limbo timer and Charger 
        determines the transition
        to PowerdOff
        If Charger is connected
        Headset will be in Limbo
        Else after Limbo timer 
        expires state transition
        to PowerdOff
    end note
    state HEADSET_FACTORY_RESET:Reset the system, Can be entered after Power On
    HEADSET_FACTORY_RESET-left->[*]
@enduml
