/* Copyright (c) 2022 Qualcomm Technologies International, Ltd. */
/* %%version */


#ifndef AUDIO_ANNOUNCEMENT_PARSER_DEBUG_H_
#define AUDIO_ANNOUNCEMENT_PARSER_DEBUG_H_


#include "lea_logging.h"

#define LEA_AUDIO_ANNOUNCEMENT_PARSER_LOG_ENABLE 0x00080000

#if (defined(LEA_AUDIO_ANNOUNCEMENT_PARSER_LOG_ENABLE) && defined(LEA_LOG_MASK) && (LEA_AUDIO_ANNOUNCEMENT_PARSER_LOG_ENABLE & LEA_LOG_MASK))

#define AUDIO_ANNOUNCEMENT_PARSER_INFO(...)  CSR_LOG_TEXT_INFO((CsrBtAudioAnnouncementParserLto, 0, __VA_ARGS__))
#define AUDIO_ANNOUNCEMENT_PARSER_WARNING(...)  CSR_LOG_TEXT_WARNING((CsrBtAudioAnnouncementParserLto, 0, __VA_ARGS__))
#define AUDIO_ANNOUNCEMENT_PARSER_ERROR(...)  CSR_LOG_TEXT_ERROR((CsrBtAudioAnnouncementParserLto, 0, __VA_ARGS__))
#define AUDIO_ANNOUNCEMENT_PARSER_PANIC(...)  {CSR_LOG_TEXT_ERROR((CsrBtAudioAnnouncementParserLto, 0, __VA_ARGS__)); CsrPanic(CSR_TECH_BT, CSR_BT_PANIC_MYSTERY, __VA_ARGS__);}

#else

#define AUDIO_ANNOUNCEMENT_PARSER_INFO(...)
#define AUDIO_ANNOUNCEMENT_PARSER_WARNING(...)
#define AUDIO_ANNOUNCEMENT_PARSER_ERROR(...)
#define AUDIO_ANNOUNCEMENT_PARSER_PANIC(...)  {CsrPanic(CSR_TECH_BT, CSR_BT_PANIC_MYSTERY, __VA_ARGS__);}

#endif

#endif /* AUDIO_ANNOUNCEMENT_PARSER_DEBUG_H_ */
