#ifndef _CSR_BT_FEATURE_PRIVATE_DEFAULT_H
#define _CSR_BT_FEATURE_PRIVATE_DEFAULT_H
/******************************************************************************
 Copyright (c) 2012-2018 Qualcomm Technologies International, Ltd.
 All Rights Reserved.
 Qualcomm Technologies International, Ltd. Confidential and Proprietary.

 REVISION:      $Revision: #1 $
******************************************************************************/
/* #undef CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES */
 
#define EXCLUDE_CSR_BT_TPT_MODULE
#define EXCLUDE_CSR_BT_MDER_MODULE
#define EXCLUDE_CSR_BT_GOEP_20_MODULE
#define EXCLUDE_CSR_BT_SBC_MODULE
#define EXCLUDE_CSR_BT_PPP_MODULE
/* #undef EXCLUDE_CSR_BT_PAN_MODULE */
/* #undef EXCLUDE_CSR_BT_GATT_MODULE_OPTIONAL */


/* #undef ENABLE_TEST_TIMEOUT */
/* #undef CSR_BT_TESTER_USE_WRITE_THROUGH_CACHE */
/* #undef ONE_SHOT_TESTER */
#define CSR_QUAL_LOG_ENABLE
/* #undef CSR_BT_INTEROP_TEST_BUILD */

/* #undef CSR_TESTER_PERFORMANCE_BARE_BONES */
/* #undef CSR_TESTER_PERFORMANCE_HANDSET_LOW_END */
/* #undef CSR_TESTER_PERFORMANCE_HANDSET_MID_END */
/* #undef CSR_TESTER_PERFORMANCE_HANDSET_HIGH_END */
/* #undef CSR_TESTER_PERFORMANCE_HANDSET_HIGH_END_AMP */
/* #undef CSR_TESTER_PERFORMANCE_HANDSET_HIGH_END_AMP_LE */
/* #undef CSR_TESTER_PERFORMANCE_CARKIT_LOW_END */
/* #undef CSR_TESTER_PERFORMANCE_CARKIT_HIGH_END */
/* #undef CSR_TESTER_PERFORMANCE_CARKIT_HIGH_END_AMP_LE */


/* #undef EXCLUDE_CSR_BT_BNEP_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_GAP_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_L2CAP_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_PPI_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_RFCOMM_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_SDP_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_SPP_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_SAP_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_PPI_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_BT_SYNC_SPEC_TEST_CASES */
/* #undef EXCLUDE_CSR_LOOPING_TEST_CASES */
/* #undef CSR_BT_AUDIO_QUALITY_ONCHIP */
/* #undef INSTALL_AES */
/* #undef CSR_BT_TESTER_USE_GEMINI_A12_HARDWARE */
/* #undef CSR_BT_TESTER_PRIMA_PROFILING */
#define EXCLUDE_L2CAP_CLS_CLR_TESTCASES
/* #undef CSR_BT_CROSS_PLATFORM_EXECUTION */
/* #undef CSR_BT_MPMD_2_DEVICE_TEST */
#define CSR_BT_MPMD_3_DEVICE_TEST
/* #undef CSR_BT_MPMD_4_DEVICE_TEST */
/* #undef CSR_BT_MPMD_5_DEVICE_TEST */
/* #undef CSR_BT_MPMD_7_DEVICE_TEST */
/* #undef CSR_BT_MPMD_TEST_FRAMEWORK */

/* #undef CSR_BT_DISABLE_H7_CTKD */
/* #undef CSR_SCARLET_AUTOMATION_FRW */

/* #undef CSR_BT_APP_AUTO_ACCEPT_PAIRING */
/* #undef EXCLUDE_CSR_BT_GATT_MODULE_SERVICE_CHANGED_DISCOVERY */
/* #undef CSR_BT_RESTART_DEVICE_SEARCH */

/* #undef INSTALL_LE_DEBUG_TEST_MODE */
#define EXCLUDE_CSR_BT_TEST_MODULE
/* #undef CSR_BT_BUILD_SYNERGY_LITE */
/* #undef CSR_BT_PTS_EXECUTION */
#endif /* _CSR_BT_FEATURE_PRIVATE_DEFAULT_H */
